apiVersion: skaffold/v3
kind: Config
metadata:
  name: hello-flask

build:
  cluster:
    dockerConfig:
      secretName: kaniko-secret
  artifacts:
  - image: hello-flask

deploy:
  helm:
    releases:
      - name: myapp
        chartPath: ./
        setValues:
          image: logmower-operator
          greeting: Heya Lauri!
          hostname: heya-lauri
